In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[8499, 9919, 7383, 5404], [8499, 9919, 7383, 6470], [8499, 6865, 7383, 6350], [1056, 7860, 6383, 3646, 3276], [1056, 7860, 6383, 3646, 7180], [2485, 8499, 8503, 7383, 6979], [5569, 51, 9908, 3646]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8499 9919 7383 5404]
 [   0    0    0    0 8499 9919 7383 6470]
 [   0    0    0    0 8499 6865 7383 6350]
 [   0    0    0 1056 7860 6383 3646 3276]
 [   0    0    0 1056 7860 6383 3646 7180]
 [   0    0    0 2485 8499 8503 7383 6979]
 [   0    0    0    0 5569   51 9908 3646]]


In [9]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 62ms/step
[[[ 0.03119154 -0.02005847 -0.04014742 -0.04825771  0.04752215
   -0.02144678  0.02659111  0.01737596 -0.02818259 -0.00478172]
  [ 0.03119154 -0.02005847 -0.04014742 -0.04825771  0.04752215
   -0.02144678  0.02659111  0.01737596 -0.02818259 -0.00478172]
  [ 0.03119154 -0.02005847 -0.04014742 -0.04825771  0.04752215
   -0.02144678  0.02659111  0.01737596 -0.02818259 -0.00478172]
  [ 0.03119154 -0.02005847 -0.04014742 -0.04825771  0.04752215
   -0.02144678  0.02659111  0.01737596 -0.02818259 -0.00478172]
  [ 0.01978971  0.04464206 -0.0035151   0.02446849 -0.0349697
   -0.00776155 -0.01308941  0.00727992 -0.01832854 -0.0055022 ]
  [ 0.01547058 -0.03343748 -0.04311989 -0.03898085 -0.0285068
    0.00257448 -0.04552536 -0.04492669 -0.02166582 -0.0145592 ]
  [ 0.04397449 -0.0273185  -0.00575211  0.03958938  0.01285445
    0.0198444   0.02037894 -0.02150446  0.04457161  0.02370015]
  [ 0.00871378  0.0413031   0.01909008  0.03034433 -0.0144290

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 8499, 9919, 7383, 5404])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 32ms/step


array([[ 0.03119154, -0.02005847, -0.04014742, -0.04825771,  0.04752215,
        -0.02144678,  0.02659111,  0.01737596, -0.02818259, -0.00478172],
       [ 0.03119154, -0.02005847, -0.04014742, -0.04825771,  0.04752215,
        -0.02144678,  0.02659111,  0.01737596, -0.02818259, -0.00478172],
       [ 0.03119154, -0.02005847, -0.04014742, -0.04825771,  0.04752215,
        -0.02144678,  0.02659111,  0.01737596, -0.02818259, -0.00478172],
       [ 0.03119154, -0.02005847, -0.04014742, -0.04825771,  0.04752215,
        -0.02144678,  0.02659111,  0.01737596, -0.02818259, -0.00478172],
       [ 0.01978971,  0.04464206, -0.0035151 ,  0.02446849, -0.0349697 ,
        -0.00776155, -0.01308941,  0.00727992, -0.01832854, -0.0055022 ],
       [ 0.01547058, -0.03343748, -0.04311989, -0.03898085, -0.0285068 ,
         0.00257448, -0.04552536, -0.04492669, -0.02166582, -0.0145592 ],
       [ 0.04397449, -0.0273185 , -0.00575211,  0.03958938,  0.01285445,
         0.0198444 ,  0.02037894, -0.02150446